config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users
      root "home#index"
    namespace :admin do
      root "portfolios#edit", id: 4
      resources :portfolios, except: [:index]
    end

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  mount_uploader :avatar, PortfolioUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/portfolios_controller.rb
class Admin::PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @portfolios = Portfolio.all
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

      if @portfolio.save
        redirect_to [:admin, @portfolio], notice: 'Portfolio was successfully created.'
      else
        render :new
      end
  end

  def update
      if @portfolio.update(portfolio_params)
        redirect_to [:admin, @portfolio], notice: 'Portfolio was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @portfolio.destroy
    redirect_to admin_portfolios_url, notice: 'Portfolio was successfully destroyed.'
  end

  private

    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end


    def portfolio_params
      params.require(:portfolio).permit(:name, :degree, :phone, :professional_history, :avatar)
    end
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @portfolio = Portfolio.find(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/admin/portfolios/_form.html.erb
<%= form_for [:admin, @portfolio] do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Graduação" %><br>
    <%= f.text_field :degree, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Contato" %><br>
    <%= f.text_field :phone, class: "Contato form-control" %>
  </div>
  <div class="field">
    <%= f.label "Histórico Profissional" %><br>
    <%= f.text_field :professional_history, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "Foto" %><br>
    <%= f.file_field :avatar %>
  </div><br>
  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-info btn-sm btn-block" %>
  </div><br>
<% end %>

app/views/admin/portfolios/edit.html.erb
<div class="jumbotron col-sm-5 col-sm-offset-3">
  <h1>Editar Portfolio</h1>
  <%= render 'form' %>
  <%= link_to 'Exibir', [:admin, @portfolio], class: "btn btn-primary btn-sm btn-block" %>
</div>

app/views/admin/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

Usuário logado com email: <%= current_user.email %>

<%= link_to "Sair", destroy_user_session_path, method: :delete %>
<h1>Listing Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Degree</th>
      <th>Phone</th>
      <th>Professional history</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.name %></td>
        <td><%= portfolio.degree %></td>
        <td><%= portfolio.phone %></td>
        <td><%= portfolio.professional_history %></td>
        <td><%= portfolio.avatar %></td>
        <td><%= link_to 'Show', [:admin,portfolio] %></td>
        <td><%= link_to 'Edit', edit_admin_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', [:admin, portfolio], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_admin_portfolio_path %>

app/views/admin/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_portfolios_path %>

app/views/admin/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @portfolio.degree %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @portfolio.phone %>
</p>

<p>
  <strong>Professional history:</strong>
  <%= @portfolio.professional_history %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @portfolio.avatar %>
</p>

<%= link_to 'Edit', edit_admin_portfolio_path(@portfolio) %>

app/views/home/index.html.erb
<div class="col-sm-12">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://previews.123rf.com/images/cherniga/cherniga1307/cherniga130700011/21608533-A-beautiful-ruby-gems-objects--Stock-Vector-ruby-gradient-diamond.jpg" alt="...">
        <div class="carousel-caption">
          Ruby
        </div>
      </div>
      <div class="item">
        <%= image_tag(@portfolio.avatar)%>
        <div class="carousel-caption">
          ...
        </div>
      </div>
      TESTE
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    </div>
  <div class="col-sm-6 col-sm-offset-4">
    <div class="col-sm-3">
      <h3><%= @portfolio.name %></h3>
    </div>

    <div class="col-sm-3">
      <%= image_tag(@portfolio.avatar) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portifolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>


  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Portfolio</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.email %></li>
          <li class="Ações">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Separated link</a></li>
              <li> <%= link_to "Sair", destroy_user_session_path, method: :delete %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end  %>
<%= yield %>

</body>
</html>